[env]
UCLIBC_IMAGE = "tmp/rust-uclibc:latest"
X86_IMAGE = "messense/rust-musl-cross:x86_64-musl"

[tasks.bin-arps]
env = { "C_APP" = "cargo-arps"}
script = '''
cargo build --no-default-features --release
del .\\target\\%C_APP%.exe
upx.exe --best --lzma -o ./target/%C_APP%.exe ./target/release/%C_APP%.exe
'''

[tasks.x86-bin]
condition = { env_set = [ "UCLIBC_IMAGE", "C_APP" ], platforms = ["windows"] }
script = '''
@echo off
SETLOCAL EnableDelayedExpansion
set "line="
set "tok= && "
for %%a in (
"cargo build --bin %C_APP% --no-default-features --release"
"rm -rf target/%C_APP%-x86 "
"upx --best --lzma -o ./target/%C_APP%-x86 ./target/x86_64-unknown-linux-musl/release/%C_APP%"
) do  (
set line=!line!%%~a!tok!
)
rem set line="%line:~0,-4%"
@echo on
docker run --rm -it -v %userprofile%\.git-credentials:/root/.git-credentials ^
    -v %cd%:/home/rust/src ^
    -v %userprofile%\.cargo\registry:/usr/local/cargo/registry ^
    -v %userprofile%\.cargo\/git:/usr/local/cargo/git ^
    %X86_IMAGE% ^
    sh -c "%line:~0,-4%"
'''